Add `upload_to_figshare.py` and replace local data-loading with cached Figshare downloads (#13)
* use load_train_test() to load wbm-summary in data.py (closes #10)

* fetch_process_wbm_dataset.py wrap urllib.request.urlretrieve in try/except (closes #12)

* add scripts/upload_to_figshare.py for publishing data files to figshare

* add data/figshare dir with readme and FIGSHARE in __init__.py

* change load_train_test() to load files from figshare instead of GitHub (closes #11)

* class Files issue warning when accessing a file path that doesn't exist

* docs recommend --depth 1 for git clone

* fix tests/test_data.py

* add auto-generated data/figshare/1.0.0.json

* pyproject.toml drop unused [tool.setuptools.package-data] matbench_discovery = ["data/mp/*.json"]

* fix AttributeError: 'DataFrame' object has no attribute 'material_id'