Refactor `discovery.write_metrics_to_yaml` and `geo_opt.write_metrics_to_yaml` to use DRY `update_yaml_at_path` (#208)
* add update_yaml_at_path() utility function with comment preservation

- supports creating new nested paths dynamically
- preserves YAML comments and handles CommentedMap objects
- includes input validation for dotted path format
- new unit tests in `test_data.py`

* refactor `write_metrics_to_yaml()` in discovery and geo_opt modules to use new update_yaml_at_path

- removes redundant YAML loading and writing boilerplate
- update corresponding test cases
- restore code in preds/discovery.py to calculate discovery metrics directly from df_preds, needed since loading df_metrics from YAML would be circular when trying to write metrics YAML

* add missing .key in model scripts

* fix tests

FAILED tests/metrics/test_geo_opt_metrics.py::test_write_geo_opt_metrics_to_yaml[metrics_data0-expected_yaml0-0.01-test/path/analysis.csv.gz] - ValueError: Invalid dotted path: metrics.geo_opt.symprec=1e-2
FAILED tests/metrics/test_geo_opt_metrics.py::test_write_geo_opt_metrics_to_yaml[metrics_data1-expected_yaml1-0.01-test/path/analysis-nan.csv.gz] - ValueError: Invalid dotted path: metrics.geo_opt.symprec=1e-2
====== 2 failed, 375 passed