Start work on website to host docs and display interactive leaderboard (#3)
* initial commit for website

* embed pdf figures on landing page

requires removing single quotes from file names to avoid build errors

rendering chunks (1)...[vite:esbuild-transpile] Transform failed with 1 error:
_app/immutable/components/pages/_page.svelte-c6406821.js:5:97: ERROR: Expected ")" but found "true"

Expected ")" but found "true"
3  |  const __vite_glob_0_0 = ""+new URL('../../assets/2022-08-16-m3gnet-wbm-hull-dist-hist-99f39fe9.pdf', import.meta.url).href+"";
4  |
5  |  const __vite_glob_0_1 = ""+new URL('../../assets/2022-08-25-wren-wbm-hull-dist-hist-energy_type_'true'-criterion_'energy'-7a843898.pdf', import.meta.url).href+"";
   |                                                                                                   ^
6  |
7  |  const __vite_glob_0_2 = ""+new URL('../../assets/2022-09-15-precision-recall-vs-calc-count-1c45e983.pdf', import.meta.url).href+""

* add pages how-to-use/+page.svx and about-the-data/+page.svx

center readme header and show favicon

* show plotly precision-recall curves as Svelte component on landing page

* add auto-generated API docs to site

rm vitest config

* add data descriptions to site/src/routes/how-to-use/+page.svx

fix favicon being cropped on the left

* compress figures/2022-12-05-precision-recall-curves.svelte to 1 line and round floats to 3 dp

* fix eslint in pre-commit.ci not finding config file