DRY workflows (#8)
* DRY workflows

* rename scripts/(difficult_structures->analyze_failure_cases).py and add per-elem test set energy std dev

* fix site/src/figs/hist-largest-each-errors-fp-diff-models.svelte title

* update deps

* extract per-element EACH errors ptable heatmap into component and move to main /models page

add option to normalize errors by elem test set std

* fix GH pages error matbench-discovery/site does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Error: Process completed with exit code 1.

* fix error matbench-discovery has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.