Refactor `Files`, `DataFiles` and `PredFiles` to be `StrEnums` (#114)
* breaking: refactor Files class to StrEnum

* refactor PredFiles to enum as well, using metaclass FilesMeta

needed to pass sublassing kwarg that are set as class attributes before __new__ is called. __init_subclass__ is usually the place to handle subclassing kwargs but is called only after __new__, i.e. not suitable for Enums

* drop FilesMeta meta class, just do abs_path construction with base_dir in path property

* path property only input() if is_ipython or sys.stdin.isatty()

* fix matbench_discovery/data.py:120: in __new__
    obj._value_ = file_path.split("/")[-1]  # use file name as enum value
E   AttributeError: 'dict' object has no attribute 'split'

* fix test_df_metrics missing_cols